import {
  COMM,
  FARM,
  FLAT,
  HOUSE_ISB,
  HOUSE_LUX,
  HOUSE_SM,
  PENT,
  PLOT,
  PROJ,
  SHOP,
} from "./photos";
import type { Agent, AreaGuide, BlogPost, Project, Property, SearchParams } from "./types";

const A = {
  drawing: "Drawing Room",
  dining: "Dining Room",
  kitchen: "Kitchen",
  powder: "Powder Room",
  store: "Store",
  garden: "Lawn / Garden",
  parking: "Parking",
  elec: "Electricity",
  gas: "Sui Gas",
  water: "Water",
  sewer: "Sewerage",
  mosque: "Mosque nearby",
  park: "Park nearby",
  school: "School nearby",
  servant: "Servant Quarter",
  terrace: "Terrace",
  study: "Study",
  ac: "Central AC",
  gen: "Backup Generator",
  sec: "Society Security",
  lift: "Elevator",
  furn: "Furnished",
  pool: "Swimming Pool",
  jac: "Jacuzzi",
};

const HOME = [
  A.drawing,
  A.dining,
  A.kitchen,
  A.parking,
  A.elec,
  A.gas,
  A.water,
  A.sewer,
  A.sec,
  A.park,
];

export const AGENTS: Agent[] = [
  {
    id: "prime-lhr",
    name: "Hassan Malik",
    agency: "Prime Properties",
    city: "Lahore",
    phone: "03008451211",
    listings: 86,
    experience: 14,
    specialty: "DHA, Bahria Town & Gulberg",
    initials: "HM",
  },
  {
    id: "skyline-khi",
    name: "Ayesha Qureshi",
    agency: "Skyline Realtors",
    city: "Karachi",
    phone: "03215550908",
    listings: 64,
    experience: 9,
    specialty: "DHA, Clifton & Sea View",
    initials: "AQ",
  },
  {
    id: "capital-isb",
    name: "Omar Khattak",
    agency: "Capital Homes",
    city: "Islamabad",
    phone: "03335678102",
    listings: 51,
    experience: 11,
    specialty: "F-sectors, DHA & B-17",
    initials: "OK",
  },
  {
    id: "north-rwp",
    name: "Sana Raza",
    agency: "Northgate Associates",
    city: "Rawalpindi",
    phone: "03124789011",
    listings: 38,
    experience: 7,
    specialty: "Bahria Town & DHA",
    initials: "SR",
  },
  {
    id: "canal-lhr",
    name: "Bilal Sheikh",
    agency: "Canal View Estates",
    city: "Lahore",
    phone: "03027773445",
    listings: 72,
    experience: 16,
    specialty: "Johar Town, Model Town, Al Kabir",
    initials: "BS",
  },
  {
    id: "harbour-khi",
    name: "Farhan Ali",
    agency: "Harbour Block",
    city: "Karachi",
    phone: "03452119876",
    listings: 44,
    experience: 8,
    specialty: "Scheme 33, Gulshan, Jauhar",
    initials: "FA",
  },
  {
    id: "margalla-isb",
    name: "Nadia Rehman",
    agency: "Margalla Listings",
    city: "Islamabad",
    phone: "03009881234",
    listings: 29,
    experience: 6,
    specialty: "E-11, F-10, apartments",
    initials: "NR",
  },
  {
    id: "multan-gate",
    name: "Usman Javed",
    agency: "Chenab Realty",
    city: "Multan",
    phone: "03016334455",
    listings: 22,
    experience: 10,
    specialty: "DHA Multan & Model Town",
    initials: "UJ",
  },
];

export const PROPERTIES: Property[] = [
  {
    id: "lhr-dha5-1k",
    title: "1 Kanal designer house, DHA Phase 5 Block C",
    purpose: "buy",
    category: "house",
    city: "Lahore",
    location: "DHA Defence",
    areaName: "Phase 5, Block C",
    price: 52_000_000,
    beds: 5,
    baths: 6,
    areaSqft: 5445,
    images: HOUSE_LUX,
    description:
      "Corner 1 Kanal residence with double-height drawing, imported kitchen, and a landscaped lawn. Solid teak doors, Italian tiles, and a separate servant wing. Walking distance to DHA Phase 5 commercial broadway.",
    amenities: [...HOME, A.servant, A.ac, A.gen, A.study, A.terrace],
    yearBuilt: 2022,
    floors: 2,
    agencyId: "prime-lhr",
    badges: ["superhot", "verified", "platinum", "featured"],
    createdAt: "2026-08-18",
    featured: true,
  },
  {
    id: "lhr-dha6-10m",
    title: "10 Marla brand-new house in DHA Phase 6",
    purpose: "buy",
    category: "house",
    city: "Lahore",
    location: "DHA Defence",
    areaName: "Phase 6, Block B",
    price: 31_500_000,
    beds: 4,
    baths: 5,
    areaSqft: 2722,
    images: HOUSE_SM,
    description:
      "Just completed 10 Marla home with car porch for two, powder room at entrance, and a roof terrace. Ideal for a family that wants DHA access without a full kanal budget.",
    amenities: [...HOME, A.terrace, A.gen],
    yearBuilt: 2026,
    floors: 2,
    agencyId: "prime-lhr",
    badges: ["hot", "verified"],
    createdAt: "2026-08-20",
  },
  {
    id: "lhr-bahria-c-5m",
    title: "5 Marla near-park house, Bahria Town Sector C",
    purpose: "buy",
    category: "house",
    city: "Lahore",
    location: "Bahria Town",
    areaName: "Sector C",
    price: 18_750_000,
    beds: 3,
    baths: 4,
    areaSqft: 1361,
    images: HOUSE_SM,
    description:
      "Facing a neighbourhood park. Open kitchen, three bedrooms with attached baths, and a tiled terrace. Society security and nearby mosque, school and commercial.",
    amenities: [...HOME, A.mosque, A.school],
    yearBuilt: 2021,
    floors: 2,
    agencyId: "canal-lhr",
    badges: ["hot", "verified"],
    createdAt: "2026-08-12",
    featured: true,
  },
  {
    id: "lhr-johar-5m",
    title: "5 Marla grey-plus house, Johar Town Block G",
    purpose: "buy",
    category: "house",
    city: "Lahore",
    location: "Johar Town",
    areaName: "Block G",
    price: 16_400_000,
    beds: 4,
    baths: 4,
    areaSqft: 1361,
    images: HOUSE_SM,
    description:
      "Solid grey structure with finishing in progress — buyer can pick tiles and kitchen. Close to Emporium and Canal Road. Possession-ready structure.",
    amenities: [A.parking, A.elec, A.gas, A.water, A.sewer, A.kitchen],
    yearBuilt: 2025,
    floors: 2,
    agencyId: "canal-lhr",
    badges: ["verified"],
    createdAt: "2026-08-02",
  },
  {
    id: "lhr-alkabir-3m",
    title: "3 Marla 4-bed house, Al Kabir Town Phase 2",
    purpose: "buy",
    category: "house",
    city: "Lahore",
    location: "Al Kabir Town",
    areaName: "Phase 2",
    price: 8_900_000,
    beds: 4,
    baths: 4,
    areaSqft: 817,
    images: HOUSE_SM,
    description:
      "Compact 3 Marla family house on a 30-foot road. Four bedrooms over two floors, car porch, and a small terrace. Built for first-time buyers and investors.",
    amenities: [A.kitchen, A.parking, A.elec, A.gas, A.water, A.sewer, A.mosque],
    yearBuilt: 2024,
    floors: 2,
    agencyId: "canal-lhr",
    badges: ["hot"],
    createdAt: "2026-08-21",
    featured: true,
  },
  {
    id: "lhr-model-2k",
    title: "2 Kanal classic bungalow, Model Town Block H",
    purpose: "buy",
    category: "house",
    city: "Lahore",
    location: "Model Town",
    areaName: "Block H",
    price: 125_000_000,
    beds: 6,
    baths: 7,
    areaSqft: 10890,
    images: HOUSE_LUX,
    description:
      "Wide-front bungalow on a quiet Model Town block. Mature trees, separate guest wing, basement lounge and a large lawn. Title is clear, tax paid.",
    amenities: [...HOME, A.servant, A.ac, A.gen, A.study, A.pool],
    yearBuilt: 2008,
    floors: 2,
    agencyId: "prime-lhr",
    badges: ["platinum", "featured", "verified"],
    createdAt: "2026-07-28",
  },
  {
    id: "lhr-gulberg-flat",
    title: "3-bed apartment on Main Boulevard, Gulberg",
    purpose: "buy",
    category: "flat",
    city: "Lahore",
    location: "Gulberg",
    areaName: "Main Boulevard",
    price: 28_000_000,
    beds: 3,
    baths: 3,
    areaSqft: 1900,
    images: FLAT,
    description:
      "Upper-floor flat in a maintained building with lift and generator. Drawing, dining, three bedrooms and two car parks. Walk to MM Alam restaurants.",
    amenities: [A.drawing, A.dining, A.kitchen, A.lift, A.gen, A.parking, A.ac],
    yearBuilt: 2016,
    floors: 1,
    agencyId: "prime-lhr",
    badges: ["verified"],
    createdAt: "2026-08-09",
  },
  {
    id: "lhr-askari-11",
    title: "1 Kanal house in Askari 11, Sector B",
    purpose: "buy",
    category: "house",
    city: "Lahore",
    location: "Askari",
    areaName: "Askari 11, Sector B",
    price: 39_000_000,
    beds: 5,
    baths: 6,
    areaSqft: 5445,
    images: HOUSE_LUX,
    description:
      "Gated Askari living with 24/7 security. Five bedrooms, two kitchens, and a covered car porch. Close to the Askari commercial and mosque.",
    amenities: [...HOME, A.servant, A.gen, A.mosque, A.sec],
    yearBuilt: 2018,
    floors: 2,
    agencyId: "prime-lhr",
    badges: ["hot", "platinum"],
    createdAt: "2026-08-05",
  },
  {
    id: "lhr-parkview-plot",
    title: "1 Kanal residential plot, Park View City",
    purpose: "buy",
    category: "plot",
    city: "Lahore",
    location: "Park View City",
    areaName: "Block D",
    price: 12_500_000,
    areaSqft: 5445,
    images: PLOT,
    description:
      "Level 1 Kanal plot on a 60-foot road. Development charges paid. Ideal for a custom home near Ring Road and the upcoming commercial strip.",
    amenities: [A.elec, A.gas, A.water, A.sewer, A.sec, A.park],
    agencyId: "canal-lhr",
    badges: ["hot", "verified"],
    createdAt: "2026-08-16",
    plotType: "residential",
  },
  {
    id: "lhr-bahria-plot-5",
    title: "5 Marla plot, Bahria Orchard Phase 2",
    purpose: "buy",
    category: "plot",
    city: "Lahore",
    location: "Bahria Orchard",
    areaName: "Phase 2",
    price: 4_350_000,
    areaSqft: 1361,
    images: PLOT,
    description:
      "West-open 5 Marla plot. Transfer in the owner's name. Society is occupied with nearby school and masjid.",
    amenities: [A.elec, A.water, A.sewer, A.sec, A.mosque, A.school],
    agencyId: "canal-lhr",
    badges: ["verified"],
    createdAt: "2026-08-11",
    plotType: "residential",
  },
  {
    id: "lhr-farm-raiwind",
    title: "8 Kanal Spanish-theme farmhouse, Bedian / Raiwind",
    purpose: "buy",
    category: "farmhouse",
    city: "Lahore",
    location: "Raiwind Road",
    areaName: "Bedian Road",
    price: 150_000_000,
    beds: 6,
    baths: 7,
    areaSqft: 43560,
    images: FARM,
    description:
      "Gated farmhouse with pool, guest cottages, orchard and a long driveway. Built for weekend living twenty minutes from DHA.",
    amenities: [...HOME, A.pool, A.servant, A.gen, A.ac, A.jac],
    yearBuilt: 2019,
    floors: 2,
    agencyId: "prime-lhr",
    badges: ["superhot", "platinum", "featured"],
    createdAt: "2026-08-01",
    featured: true,
  },
  {
    id: "lhr-gulberg-shop",
    title: "Ground-floor shop, Gulberg MM Alam",
    purpose: "buy",
    category: "commercial",
    city: "Lahore",
    location: "Gulberg",
    areaName: "MM Alam Road",
    price: 45_000_000,
    areaSqft: 900,
    images: SHOP,
    description:
      "Prime 100 Sq. Yd. shop with mezzanine. Heavy footfall, restaurant and retail neighbours. Clear title, vacant possession.",
    amenities: [A.elec, A.water, A.parking, A.gen],
    agencyId: "prime-lhr",
    badges: ["platinum", "verified"],
    createdAt: "2026-07-22",
    plotType: "commercial",
  },
  {
    id: "lhr-dha-rent-1k",
    title: "1 Kanal furnished house for rent, DHA Phase 4",
    purpose: "rent",
    category: "house",
    city: "Lahore",
    location: "DHA Defence",
    areaName: "Phase 4, Block FF",
    price: 350_000,
    beds: 5,
    baths: 6,
    areaSqft: 5445,
    images: HOUSE_LUX,
    description:
      "Family house with furniture, generator and gardener. Available from 1 September. Two months deposit, 12-month lease preferred.",
    amenities: [...HOME, A.furn, A.ac, A.gen, A.servant],
    yearBuilt: 2017,
    floors: 2,
    agencyId: "prime-lhr",
    badges: ["hot", "verified"],
    createdAt: "2026-08-19",
    furnished: "furnished",
  },
  {
    id: "lhr-bahria-rent-5m",
    title: "5 Marla house on rent, Bahria Town Sector D",
    purpose: "rent",
    category: "house",
    city: "Lahore",
    location: "Bahria Town",
    areaName: "Sector D",
    price: 75_000,
    beds: 3,
    baths: 3,
    areaSqft: 1361,
    images: HOUSE_SM,
    description:
      "Unfurnished 5 Marla with separate drawing. Near the Sector D park and commercial. Families preferred.",
    amenities: [...HOME, A.park],
    yearBuilt: 2020,
    floors: 2,
    agencyId: "canal-lhr",
    badges: ["verified"],
    createdAt: "2026-08-14",
    furnished: "unfurnished",
  },
  {
    id: "lhr-askari-rent",
    title: "Upper portion 3-bed, Askari 10",
    purpose: "rent",
    category: "portion",
    city: "Lahore",
    location: "Askari",
    areaName: "Askari 10",
    price: 85_000,
    beds: 3,
    baths: 3,
    areaSqft: 1800,
    images: HOUSE_SM,
    description:
      "Independent upper portion with private stairs and one car porch. Gas and electricity separate. Quiet street inside Askari 10.",
    amenities: [A.kitchen, A.parking, A.elec, A.gas, A.water, A.sec],
    agencyId: "canal-lhr",
    badges: ["hot"],
    createdAt: "2026-08-08",
    furnished: "semi",
  },
  {
    id: "khi-dha6-500",
    title: "500 Sq. Yd. house, DHA Phase 6 Karachi",
    purpose: "buy",
    category: "house",
    city: "Karachi",
    location: "DHA Defence",
    areaName: "Phase 6",
    price: 95_000_000,
    beds: 5,
    baths: 6,
    areaSqft: 4500,
    images: HOUSE_LUX,
    description:
      "West-open 500-yard bungalow a short drive from Khayaban-e-Shaheen. Basement plus two floors, elevator provision, and a roof sit-out.",
    amenities: [...HOME, A.ac, A.gen, A.servant, A.lift],
    yearBuilt: 2020,
    floors: 3,
    agencyId: "skyline-khi",
    badges: ["superhot", "platinum", "verified", "featured"],
    createdAt: "2026-08-17",
    featured: true,
  },
  {
    id: "khi-clifton-3bed",
    title: "Sea-facing 3-bed apartment, Clifton Block 2",
    purpose: "buy",
    category: "flat",
    city: "Karachi",
    location: "Clifton",
    areaName: "Block 2",
    price: 42_000_000,
    beds: 3,
    baths: 3,
    areaSqft: 1850,
    images: PENT,
    description:
      "Corner apartment with Arabian Sea glimpse, two covered parks, and 24-hour building security. Recently renovated kitchen and baths.",
    amenities: [A.drawing, A.kitchen, A.lift, A.gen, A.sec, A.parking, A.ac],
    yearBuilt: 2012,
    agencyId: "skyline-khi",
    badges: ["hot", "verified", "featured"],
    createdAt: "2026-08-13",
  },
  {
    id: "khi-bahria-250",
    title: "250 Sq. Yd. house, Bahria Town Precinct 11",
    purpose: "buy",
    category: "house",
    city: "Karachi",
    location: "Bahria Town Karachi",
    areaName: "Precinct 11",
    price: 24_500_000,
    beds: 4,
    baths: 4,
    areaSqft: 2250,
    images: HOUSE_SM,
    description:
      "Occupied Precinct 11 house with Bahria amenities: safari park, hospital and commercial nearby. Four beds, two parks.",
    amenities: [...HOME, A.mosque, A.school, A.park],
    yearBuilt: 2023,
    floors: 2,
    agencyId: "harbour-khi",
    badges: ["hot", "verified"],
    createdAt: "2026-08-10",
  },
  {
    id: "khi-gulshan-flat",
    title: "1200 sq ft flat, Gulshan-e-Iqbal Block 13",
    purpose: "buy",
    category: "flat",
    city: "Karachi",
    location: "Gulshan-e-Iqbal",
    areaName: "Block 13-D",
    price: 18_200_000,
    beds: 3,
    baths: 3,
    areaSqft: 1200,
    images: FLAT,
    description:
      "Second-floor flat in a well-kept building near University Road. Three bedrooms, drawing and a small balcony.",
    amenities: [A.kitchen, A.lift, A.parking, A.elec, A.gas, A.water],
    yearBuilt: 2014,
    agencyId: "harbour-khi",
    badges: ["verified"],
    createdAt: "2026-08-04",
  },
  {
    id: "khi-scheme33-plot",
    title: "120 Sq. Yd. plot, Scheme 33 Gulzar-e-Hijri",
    purpose: "buy",
    category: "plot",
    city: "Karachi",
    location: "Scheme 33",
    areaName: "Gulzar-e-Hijri",
    price: 6_800_000,
    areaSqft: 1080,
    images: PLOT,
    description:
      "Residential 120-yard plot on a 40-foot road. Amenity plot nearby. Registry and mutation clean.",
    amenities: [A.elec, A.water, A.sewer],
    agencyId: "harbour-khi",
    badges: ["hot"],
    createdAt: "2026-08-07",
    plotType: "residential",
  },
  {
    id: "khi-clifton-rent",
    title: "2-bed furnished flat, Clifton Block 5",
    purpose: "rent",
    category: "flat",
    city: "Karachi",
    location: "Clifton",
    areaName: "Block 5",
    price: 180_000,
    beds: 2,
    baths: 2,
    areaSqft: 1100,
    images: FLAT,
    description:
      "Fully furnished with generator, lift and 24-hour security. Professionals and small families. Available immediately.",
    amenities: [A.furn, A.ac, A.lift, A.gen, A.parking, A.sec],
    agencyId: "skyline-khi",
    badges: ["hot", "verified"],
    createdAt: "2026-08-15",
    furnished: "furnished",
  },
  {
    id: "khi-nn-portion",
    title: "Upper portion, North Nazimabad Block H",
    purpose: "rent",
    category: "portion",
    city: "Karachi",
    location: "North Nazimabad",
    areaName: "Block H",
    price: 65_000,
    beds: 3,
    baths: 2,
    areaSqft: 1400,
    images: HOUSE_SM,
    description:
      "Airy upper portion with rooftop access. Separate meter. Close to 5-star chowrangi and schools.",
    amenities: [A.kitchen, A.terrace, A.elec, A.gas, A.water],
    agencyId: "harbour-khi",
    badges: [],
    createdAt: "2026-08-03",
    furnished: "unfurnished",
  },
  {
    id: "khi-dha-shop",
    title: "Commercial shop, DHA Phase 6 Khayaban-e-Ittehad",
    purpose: "buy",
    category: "commercial",
    city: "Karachi",
    location: "DHA Defence",
    areaName: "Phase 6, Ittehad",
    price: 38_000_000,
    areaSqft: 720,
    images: COMM,
    description:
      "Corner shop in a busy DHA commercial. Suitable for pharmacy, café or showroom. Mezzanine included.",
    amenities: [A.elec, A.parking, A.gen, A.water],
    agencyId: "skyline-khi",
    badges: ["platinum", "verified"],
    createdAt: "2026-07-30",
    plotType: "commercial",
  },
  {
    id: "khi-pent-seaview",
    title: "Penthouse with terrace, Sea View Apartments",
    purpose: "buy",
    category: "flat",
    city: "Karachi",
    location: "Clifton",
    areaName: "Sea View",
    price: 78_000_000,
    beds: 4,
    baths: 5,
    areaSqft: 3200,
    images: PENT,
    description:
      "Full-floor penthouse, private terrace and sea wind all day. Three covered parks and a store in the basement.",
    amenities: [A.drawing, A.ac, A.lift, A.gen, A.terrace, A.parking, A.sec],
    yearBuilt: 2011,
    agencyId: "skyline-khi",
    badges: ["superhot", "platinum", "featured"],
    createdAt: "2026-08-06",
    featured: true,
  },
  {
    id: "isb-f7-1k",
    title: "1 Kanal house, Islamabad F-7/3",
    purpose: "buy",
    category: "house",
    city: "Islamabad",
    location: "F-7",
    areaName: "F-7/3",
    price: 185_000_000,
    beds: 5,
    baths: 6,
    areaSqft: 5445,
    images: HOUSE_ISB,
    description:
      "Quiet F-7 street, Margalla view from the roof. Drawing, dining, five bedrooms and a landscaped lawn. CDA lease, tax paid.",
    amenities: [...HOME, A.ac, A.gen, A.servant, A.study],
    yearBuilt: 2006,
    floors: 2,
    agencyId: "capital-isb",
    badges: ["platinum", "verified", "featured"],
    createdAt: "2026-08-02",
    featured: true,
  },
  {
    id: "isb-e11-flat",
    title: "3-bed apartment, E-11/4",
    purpose: "buy",
    category: "flat",
    city: "Islamabad",
    location: "E-11",
    areaName: "E-11/4",
    price: 22_500_000,
    beds: 3,
    baths: 3,
    areaSqft: 1600,
    images: FLAT,
    description:
      "Corner flat with lift, generator and assigned parking. Close to Golra and the E-11 markaz.",
    amenities: [A.kitchen, A.lift, A.gen, A.parking, A.sec],
    yearBuilt: 2018,
    agencyId: "margalla-isb",
    badges: ["hot", "verified"],
    createdAt: "2026-08-12",
  },
  {
    id: "isb-dha2-10m",
    title: "10 Marla house, DHA Phase 2 Islamabad",
    purpose: "buy",
    category: "house",
    city: "Islamabad",
    location: "DHA Defence",
    areaName: "Phase 2, Sector G",
    price: 38_500_000,
    beds: 4,
    baths: 5,
    areaSqft: 2722,
    images: HOUSE_ISB,
    description:
      "Double-storey 10 Marla on a 50-foot road. DHA security, nearby school and commercial. Possession with original file.",
    amenities: [...HOME, A.gen, A.school, A.mosque],
    yearBuilt: 2024,
    floors: 2,
    agencyId: "capital-isb",
    badges: ["superhot", "verified", "platinum"],
    createdAt: "2026-08-19",
    featured: true,
  },
  {
    id: "isb-b17-plot",
    title: "10 Marla plot, Multi Gardens B-17",
    purpose: "buy",
    category: "plot",
    city: "Islamabad",
    location: "B-17",
    areaName: "Multi Gardens",
    price: 9_500_000,
    areaSqft: 2722,
    images: PLOT,
    description:
      "Level 10 Marla, development work on the street. Transfer through FGEHA. Good for build-and-hold.",
    amenities: [A.elec, A.water, A.sewer, A.park],
    agencyId: "capital-isb",
    badges: ["hot"],
    createdAt: "2026-08-08",
    plotType: "residential",
  },
  {
    id: "isb-bahria-5m",
    title: "5 Marla house, Bahria Town Phase 7",
    purpose: "buy",
    category: "house",
    city: "Islamabad",
    location: "Bahria Town",
    areaName: "Phase 7",
    price: 16_800_000,
    beds: 3,
    baths: 4,
    areaSqft: 1361,
    images: HOUSE_SM,
    description:
      "Near Bahria hospital and expressway. Three beds, drawing and a terrace. Occupied society with daily utilities.",
    amenities: [...HOME, A.mosque, A.school],
    yearBuilt: 2022,
    floors: 2,
    agencyId: "north-rwp",
    badges: ["verified"],
    createdAt: "2026-08-11",
  },
  {
    id: "isb-f10-rent",
    title: "2-bed flat on rent, F-10 Markaz",
    purpose: "rent",
    category: "flat",
    city: "Islamabad",
    location: "F-10",
    areaName: "F-10 Markaz",
    price: 95_000,
    beds: 2,
    baths: 2,
    areaSqft: 1050,
    images: FLAT,
    description:
      "Above commercial, lift and generator. Walking to Super Market. Professionals preferred. Semi-furnished.",
    amenities: [A.kitchen, A.lift, A.gen, A.parking],
    agencyId: "margalla-isb",
    badges: ["hot"],
    createdAt: "2026-08-16",
    furnished: "semi",
  },
  {
    id: "isb-f8-rent",
    title: "1 Kanal house on rent, F-8/2",
    purpose: "rent",
    category: "house",
    city: "Islamabad",
    location: "F-8",
    areaName: "F-8/2",
    price: 420_000,
    beds: 5,
    baths: 5,
    areaSqft: 5445,
    images: HOUSE_ISB,
    description:
      "Diplomatic-area house, lawn and servant quarter. Unfurnished. 12-month lease, embassy and corporate tenants welcome.",
    amenities: [...HOME, A.servant, A.gen, A.ac],
    agencyId: "capital-isb",
    badges: ["platinum", "verified"],
    createdAt: "2026-08-01",
    furnished: "unfurnished",
  },
  {
    id: "isb-g13-house",
    title: "10 Marla house, G-13/3",
    purpose: "buy",
    category: "house",
    city: "Islamabad",
    location: "G-13",
    areaName: "G-13/3",
    price: 29_000_000,
    beds: 4,
    baths: 4,
    areaSqft: 2722,
    images: HOUSE_ISB,
    description:
      "CDA sector house close to the G-13 markaz. Four beds, two kitchens, covered porch. Newly painted.",
    amenities: [...HOME, A.gen],
    yearBuilt: 2015,
    floors: 2,
    agencyId: "capital-isb",
    badges: ["verified"],
    createdAt: "2026-07-26",
  },
  {
    id: "rwp-bahria-10m",
    title: "10 Marla house, Bahria Town Phase 8",
    purpose: "buy",
    category: "house",
    city: "Rawalpindi",
    location: "Bahria Town",
    areaName: "Phase 8",
    price: 24_000_000,
    beds: 4,
    baths: 5,
    areaSqft: 2722,
    images: HOUSE_SM,
    description:
      "Facing a park in Phase 8. Four beds, drawing, and a terrace. Ten minutes to Bahria Expressway.",
    amenities: [...HOME, A.park, A.mosque],
    yearBuilt: 2021,
    floors: 2,
    agencyId: "north-rwp",
    badges: ["hot", "verified"],
    createdAt: "2026-08-14",
    featured: true,
  },
  {
    id: "rwp-dha-1k",
    title: "1 Kanal house, DHA Phase 1 Rawalpindi",
    purpose: "buy",
    category: "house",
    city: "Rawalpindi",
    location: "DHA Defence",
    areaName: "Phase 1",
    price: 41_000_000,
    beds: 5,
    baths: 6,
    areaSqft: 5445,
    images: HOUSE_ISB,
    description:
      "Wide-front 1 Kanal with basement lounge. DHA security and nearby commercial. Original allotment.",
    amenities: [...HOME, A.servant, A.gen, A.ac],
    yearBuilt: 2019,
    floors: 2,
    agencyId: "north-rwp",
    badges: ["platinum", "verified"],
    createdAt: "2026-08-09",
  },
  {
    id: "rwp-sat-rent",
    title: "Lower portion, Satellite Town Block B",
    purpose: "rent",
    category: "portion",
    city: "Rawalpindi",
    location: "Satellite Town",
    areaName: "Block B",
    price: 55_000,
    beds: 3,
    baths: 2,
    areaSqft: 1500,
    images: HOUSE_SM,
    description:
      "Independent lower portion with courtyard. Near commercial market and colleges.",
    amenities: [A.kitchen, A.parking, A.elec, A.gas, A.water],
    agencyId: "north-rwp",
    badges: [],
    createdAt: "2026-08-05",
    furnished: "unfurnished",
  },
  {
    id: "mul-dha-10m",
    title: "10 Marla house, DHA Multan",
    purpose: "buy",
    category: "house",
    city: "Multan",
    location: "DHA Defence",
    areaName: "Phase 1",
    price: 19_500_000,
    beds: 4,
    baths: 4,
    areaSqft: 2722,
    images: HOUSE_SM,
    description:
      "Occupied DHA Multan street. Four bedrooms, lawn strip and two parks. Clear DHA papers.",
    amenities: [...HOME, A.sec, A.mosque],
    yearBuilt: 2023,
    floors: 2,
    agencyId: "multan-gate",
    badges: ["hot", "verified"],
    createdAt: "2026-08-10",
  },
  {
    id: "fsd-civil-house",
    title: "1 Kanal house, Civil Lines Faisalabad",
    purpose: "buy",
    category: "house",
    city: "Faisalabad",
    location: "Civil Lines",
    areaName: "Club Road",
    price: 36_000_000,
    beds: 5,
    baths: 5,
    areaSqft: 5445,
    images: HOUSE_LUX,
    description:
      "Established Civil Lines bungalow near the club. Mature garden, five bedrooms and a separate garage.",
    amenities: [...HOME, A.servant, A.garden, A.gen],
    yearBuilt: 2004,
    floors: 2,
    agencyId: "canal-lhr",
    badges: ["verified"],
    createdAt: "2026-07-18",
  },
  {
    id: "pew-hayat-10m",
    title: "10 Marla house, Hayatabad Phase 3",
    purpose: "buy",
    category: "house",
    city: "Peshawar",
    location: "Hayatabad",
    areaName: "Phase 3",
    price: 27_500_000,
    beds: 4,
    baths: 5,
    areaSqft: 2722,
    images: HOUSE_ISB,
    description:
      "Quiet Hayatabad street, four beds and a lawn. Near PDA commercial and schools.",
    amenities: [...HOME, A.garden, A.school],
    yearBuilt: 2016,
    floors: 2,
    agencyId: "capital-isb",
    badges: ["verified"],
    createdAt: "2026-08-03",
  },
  {
    id: "lhr-plaza-johar",
    title: "5-storey commercial plaza, Johar Town",
    purpose: "buy",
    category: "commercial",
    city: "Lahore",
    location: "Johar Town",
    areaName: "Near Emporium",
    price: 210_000_000,
    areaSqft: 7200,
    images: COMM,
    description:
      "Income-producing plaza with ground shops and upper offices. Occupied tenants, separate meters, lift and generator.",
    amenities: [A.lift, A.gen, A.parking, A.elec, A.water],
    yearBuilt: 2013,
    floors: 5,
    agencyId: "canal-lhr",
    badges: ["platinum", "featured"],
    createdAt: "2026-07-12",
    plotType: "commercial",
  },
  {
    id: "lhr-valencia-10m",
    title: "10 Marla house, Valencia Town Block D",
    purpose: "buy",
    category: "house",
    city: "Lahore",
    location: "Valencia Town",
    areaName: "Block D",
    price: 21_000_000,
    beds: 4,
    baths: 4,
    areaSqft: 2722,
    images: HOUSE_SM,
    description:
      "Family house inside Valencia with society park and mosque. Four beds, drawing and a tiled terrace.",
    amenities: [...HOME, A.park, A.mosque],
    yearBuilt: 2018,
    floors: 2,
    agencyId: "canal-lhr",
    badges: ["verified"],
    createdAt: "2026-08-06",
  },
  {
    id: "lhr-rahbar-5m",
    title: "5 Marla house, DHA Rahbar Phase 2",
    purpose: "buy",
    category: "house",
    city: "Lahore",
    location: "DHA Rahbar",
    areaName: "Phase 2",
    price: 13_500_000,
    beds: 3,
    baths: 4,
    areaSqft: 1361,
    images: HOUSE_SM,
    description:
      "Near the Rahbar commercial. Three bedrooms, car porch, DHA security. Good rental yield.",
    amenities: [...HOME, A.sec, A.mosque],
    yearBuilt: 2024,
    floors: 2,
    agencyId: "prime-lhr",
    badges: ["hot"],
    createdAt: "2026-08-18",
  },
];

export const PROJECTS: Project[] = [
  {
    id: "park-view-city",
    name: "Park View City",
    city: "Lahore",
    location: "Lahore Ring Road",
    developer: "Vision Holdings",
    status: "Under Construction",
    priceFrom: 4_500_000,
    types: ["5 Marla", "10 Marla", "1 Kanal"],
    description:
      "Master-planned community on Ring Road with parks, a commercial boulevard and gated sectors. Plots and houses available on a 4-year plan.",
    images: PROJ,
    paymentPlan: "4-year instalments",
    size: "6,000+ Kanal",
  },
  {
    id: "capital-smart",
    name: "Capital Smart City",
    city: "Islamabad",
    location: "Motorway M-2",
    developer: "Future Development Holdings",
    status: "Under Construction",
    priceFrom: 3_800_000,
    types: ["5 Marla", "8 Marla", "10 Marla"],
    description:
      "Smart-infrastructure city west of Islamabad with overseas block, waterfront and a proposed 18-hole course.",
    images: PROJ,
    paymentPlan: "3-year instalments",
    size: "50,000+ Kanal",
  },
  {
    id: "dha-city-khi",
    name: "DHA City Karachi",
    city: "Karachi",
    location: "Super Highway",
    developer: "DHA Karachi",
    status: "Ready",
    priceFrom: 7_500_000,
    types: ["125 Sq. Yd.", "250 Sq. Yd.", "500 Sq. Yd."],
    description:
      "DHA's northern city with developed sectors, schools and a golf club. Files and developed plots both in market.",
    images: PROJ,
    paymentPlan: "Full payment / resale",
    size: "20,000+ acres",
  },
  {
    id: "lahore-smart",
    name: "Lahore Smart City",
    city: "Lahore",
    location: "Lahore–Islamabad Motorway",
    developer: "HRL",
    status: "Launch",
    priceFrom: 3_200_000,
    types: ["5 Marla", "10 Marla"],
    description:
      "New motorway community with overseas and executive blocks. Early-bird 5 Marla on a 2.5-year plan.",
    images: PROJ,
    paymentPlan: "2.5-year instalments",
    size: "10,000+ Kanal",
  },
  {
    id: "blue-world",
    name: "Blue World City",
    city: "Islamabad",
    location: "Chakri Road",
    developer: "Blue Group",
    status: "Under Construction",
    priceFrom: 2_400_000,
    types: ["5 Marla", "7 Marla", "10 Marla"],
    description:
      "Themed blocks including overseas, sports valley and waterfront. Development underway with possession in phases.",
    images: PROJ,
    paymentPlan: "4-year instalments",
    size: "40,000+ Kanal",
  },
  {
    id: "new-metro",
    name: "New Metro City",
    city: "Lahore",
    location: "GT Road / Kala Shah Kaku",
    developer: "Vision Group",
    status: "Under Construction",
    priceFrom: 2_900_000,
    types: ["3 Marla", "5 Marla", "10 Marla"],
    description:
      "GT Road community aimed at first-time buyers. 3 and 5 Marla products with a commercial strip.",
    images: PROJ,
    paymentPlan: "3-year instalments",
    size: "8,000+ Kanal",
  },
];

export const GUIDES: AreaGuide[] = [
  {
    slug: "dha-lahore",
    name: "DHA Defence",
    city: "Lahore",
    overview:
      "Lahore's most established gated address. Phases 5–8 lead house demand; Rahbar is the entry ticket. Commercial broadway in Phase 5 is the lifestyle core.",
    avgHouse: 45_000_000,
    avgPlot: 22_000_000,
    avgRent: 220_000,
    highlights: ["Gated security", "International schools", "Phase 5 broadway", "Strong resale"],
    trend: [
      { year: "2022", house: 32, plot: 16 },
      { year: "2023", house: 36, plot: 18 },
      { year: "2024", house: 40, plot: 20 },
      { year: "2025", house: 43, plot: 21 },
      { year: "2026", house: 45, plot: 22 },
    ],
    image: HOUSE_LUX[0],
  },
  {
    slug: "bahria-lahore",
    name: "Bahria Town",
    city: "Lahore",
    overview:
      "Self-contained city on the canal and Raiwind side. Sectors C–F are occupied; Orchard is the plot play. Amenities are the draw: safari, cinema, hospitals.",
    avgHouse: 19_000_000,
    avgPlot: 6_500_000,
    avgRent: 80_000,
    highlights: ["Theme park & safari", "24/7 security", "Hospitals & schools", "Ready sectors"],
    trend: [
      { year: "2022", house: 14, plot: 4.2 },
      { year: "2023", house: 15.5, plot: 4.8 },
      { year: "2024", house: 17, plot: 5.5 },
      { year: "2025", house: 18, plot: 6.1 },
      { year: "2026", house: 19, plot: 6.5 },
    ],
    image: HOUSE_SM[0],
  },
  {
    slug: "dha-karachi",
    name: "DHA Defence",
    city: "Karachi",
    overview:
      "Karachi's premium south. Phase 6 and 8 command 500-yard houses; Creek and Phase 5 lead apartments. Ittehad and Bukhari are the retail streets.",
    avgHouse: 85_000_000,
    avgPlot: 55_000_000,
    avgRent: 250_000,
    highlights: ["Sea breeze", "Khayaban commercial", "Schools & clubs", "Title security"],
    trend: [
      { year: "2022", house: 62, plot: 40 },
      { year: "2023", house: 70, plot: 44 },
      { year: "2024", house: 76, plot: 48 },
      { year: "2025", house: 81, plot: 52 },
      { year: "2026", house: 85, plot: 55 },
    ],
    image: HOUSE_LUX[0],
  },
  {
    slug: "clifton-karachi",
    name: "Clifton",
    city: "Karachi",
    overview:
      "Apartment-first neighbourhood against the sea. Block 2 and 5 are the investment core; Sea View penthouses are the trophy stock.",
    avgHouse: 48_000_000,
    avgPlot: 90_000_000,
    avgRent: 160_000,
    highlights: ["Sea View", "Boat Basin", "High-rises", "End-user demand"],
    trend: [
      { year: "2022", house: 36, plot: 70 },
      { year: "2023", house: 40, plot: 76 },
      { year: "2024", house: 43, plot: 82 },
      { year: "2025", house: 46, plot: 86 },
      { year: "2026", house: 48, plot: 90 },
    ],
    image: PENT[0],
  },
  {
    slug: "f-sectors-islamabad",
    name: "F-Sectors",
    city: "Islamabad",
    overview:
      "The capital's original sectors. F-6 and F-7 are diplomatic; F-10 and F-11 mix houses and flats. CDA leasehold, scarce plots, durable rents.",
    avgHouse: 140_000_000,
    avgPlot: 180_000_000,
    avgRent: 320_000,
    highlights: ["Margalla views", "Markaz retail", "Embassies", "CDA planning"],
    trend: [
      { year: "2022", house: 110, plot: 140 },
      { year: "2023", house: 120, plot: 150 },
      { year: "2024", house: 128, plot: 162 },
      { year: "2025", house: 135, plot: 172 },
      { year: "2026", house: 140, plot: 180 },
    ],
    image: HOUSE_ISB[0],
  },
  {
    slug: "bahria-rawalpindi",
    name: "Bahria Town",
    city: "Rawalpindi",
    overview:
      "The twin cities' largest private society. Phase 7–8 are the live sectors; Expressway access is the lifestyle unlock.",
    avgHouse: 22_000_000,
    avgPlot: 8_000_000,
    avgRent: 90_000,
    highlights: ["Expressway", "Bahria hospital", "Golf & clubs", "Deep occupancy"],
    trend: [
      { year: "2022", house: 16, plot: 5.5 },
      { year: "2023", house: 18, plot: 6.2 },
      { year: "2024", house: 19.5, plot: 7 },
      { year: "2025", house: 21, plot: 7.6 },
      { year: "2026", house: 22, plot: 8 },
    ],
    image: HOUSE_SM[0],
  },
];

export const POSTS: BlogPost[] = [
  {
    slug: "kanal-vs-marla",
    title: "Kanal, Marla and Square Yards — a buyer’s cheat sheet",
    excerpt: "Punjab talks Marla. Karachi talks yards. Here is how to convert without getting burned.",
    body: [
      "In Punjab and Islamabad, 1 Marla is 272.25 square feet and 1 Kanal is 20 Marla (5,445 sq ft). Karachi listings usually quote square yards (9 sq ft each), so a 500-yard DHA house is about 4,500 sq ft — just under a Lahore Kanal.",
      "Always ask which Marla the seller means. Some older files still use 225 sq ft. Diwaar stores every listing in square feet and lets you switch the display unit in the header.",
      "For plots, frontage matters as much as area. A 30-foot road 5 Marla will rent faster than a 20-foot road 5 Marla in the same block.",
    ],
    date: "2026-08-12",
    tag: "Guides",
    image: PLOT[0],
  },
  {
    slug: "dha-lahore-2026",
    title: "Where DHA Lahore prices actually moved in 2026",
    excerpt: "Phase 5 held. Rahbar absorbed first-time demand. Files in new sectors cooled.",
    body: [
      "Constructed 1 Kanal in Phase 5 and 6 still clears between 4.5 and 6.5 Crore depending on block and finishing. 10 Marla inventory in Phase 6 is the sweet spot for upgraders leaving Bahria.",
      "DHA Rahbar remains the volume story: 5 Marla houses around 1.3–1.6 Crore with genuine end-user traffic. Plot files in newer phases are slower — cash buyers prefer possession.",
      "If you are investing, occupied streets with a park or commercial nearby still beat paper profits on undeveloped files.",
    ],
    date: "2026-08-04",
    tag: "Market",
    image: HOUSE_LUX[0],
  },
  {
    slug: "home-loan-pakistan",
    title: "Home loans in Pakistan: what 2026 rates mean for a 5 Marla",
    excerpt: "Markup is still high. The calculator on Diwaar shows why a larger down payment wins.",
    body: [
      "Bank housing markup has eased from the 2023 peak but still sits in the mid-to-high teens for conventional products. Islamic diminishing musharakah is similar once you include rent.",
      "On a 1.5 Crore house with 30% down over 15 years, the monthly instalment can rival DHA rents. Run the numbers on Tools before you sign a token.",
      "Some developers still offer in-house plans at 0% markup with a higher list price — compare the total outflow, not the headline rate.",
    ],
    date: "2026-07-22",
    tag: "Finance",
    image: HOUSE_SM[0],
  },
  {
    slug: "first-house-checklist",
    title: "First house in Lahore: a 12-point paperwork checklist",
    excerpt: "Token is not a contract. Registry, fard, tax and society NOC still decide if you own it.",
    body: [
      "Ask for a recent fard, CNIC of the owner, society transfer rules and any surviving bank charge. In DHA, confirm the membership and transfer fee before you lock a date.",
      "Check commercialisation status on corner plots — a residential price on a commercialised plot is a gift; the reverse is a trap.",
      "Walk the house at noon and at night. Water pressure, sewer smell and generator load only show up when the street is alive.",
    ],
    date: "2026-07-08",
    tag: "Guides",
    image: HOUSE_SM[0],
  },
];

export function getAgent(id: string) {
  return AGENTS.find((a) => a.id === id);
}

export function getProperty(id: string, extra: Property[] = []) {
  return extra.find((p) => p.id === id) ?? PROPERTIES.find((p) => p.id === id);
}

export function locationsInCity(city: string, extra: Property[] = []): string[] {
  const set = new Set<string>();
  for (const p of [...extra, ...PROPERTIES]) {
    if (p.city === city) set.add(p.location);
  }
  return [...set].sort();
}

export function filterProperties(list: Property[], params: SearchParams): Property[] {
  let out = list.filter((p) => {
    if (params.purpose && p.purpose !== params.purpose) return false;
    if (params.city && p.city !== params.city) return false;
    if (params.location && p.location !== params.location) return false;
    if (params.type && p.category !== params.type) return false;
    if (params.beds && (p.beds ?? 0) < params.beds) return false;
    if (params.minPrice && p.price < params.minPrice) return false;
    if (params.maxPrice && p.price > params.maxPrice) return false;
    if (params.minArea && p.areaSqft < params.minArea) return false;
    if (params.maxArea && p.areaSqft > params.maxArea) return false;
    if (params.q) {
      const hay = `${p.title} ${p.location} ${p.areaName} ${p.city} ${p.category}`.toLowerCase();
      if (!hay.includes(params.q.toLowerCase())) return false;
    }
    return true;
  });
  switch (params.sort) {
    case "price-asc":
      out = [...out].sort((a, b) => a.price - b.price);
      break;
    case "price-desc":
      out = [...out].sort((a, b) => b.price - a.price);
      break;
    case "area-desc":
      out = [...out].sort((a, b) => b.areaSqft - a.areaSqft);
      break;
    default:
      out = [...out].sort((a, b) => b.createdAt.localeCompare(a.createdAt));
  }
  return out;
}

export function similarTo(p: Property, extra: Property[] = []): Property[] {
  return [...extra, ...PROPERTIES]
    .filter(
      (x) =>
        x.id !== p.id &&
        x.purpose === p.purpose &&
        (x.city === p.city || x.category === p.category),
    )
    .slice(0, 4);
}

export function countByLocation(city: string, purpose: "buy" | "rent", category?: Property["category"]) {
  const map = new Map<string, number>();
  for (const p of PROPERTIES) {
    if (p.city !== city || p.purpose !== purpose) continue;
    if (category && p.category !== category) continue;
    map.set(p.location, (map.get(p.location) ?? 0) + 1);
  }
  return [...map.entries()].sort((a, b) => b[1] - a[1]);
}
