/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AddRouteImport } from './routes/add'
import { Route as AgenciesRouteImport } from './routes/agencies'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CitiesRouteImport } from './routes/cities'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as InvestRouteImport } from './routes/invest'
import { Route as LoansRouteImport } from './routes/loans'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MapsRouteImport } from './routes/maps'
import { Route as MyAdsRouteImport } from './routes/my-ads'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PayRouteImport } from './routes/pay'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PropertyIndexRouteImport } from './routes/property-index'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as WantedRouteImport } from './routes/wanted'
import { Route as AgenciesIdRouteImport } from './routes/agencies.$id'
import { Route as AgentsIdRouteImport } from './routes/agents.$id'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as CommunityIdRouteImport } from './routes/community.$id'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as LocationsCityRouteImport } from './routes/locations.$city'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as PropertyIdRouteImport } from './routes/property.$id'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as LocationsCityAreaRouteImport } from './routes/locations.$city.$area'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenciesRoute = AgenciesRouteImport.update({
  id: '/agencies',
  path: '/agencies',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesRoute = CitiesRouteImport.update({
  id: '/cities',
  path: '/cities',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestRoute = InvestRouteImport.update({
  id: '/invest',
  path: '/invest',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansRoute = LoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsRoute = MapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => rootRouteImport,
} as any)
const MyAdsRoute = MyAdsRouteImport.update({
  id: '/my-ads',
  path: '/my-ads',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyIndexRoute = PropertyIndexRouteImport.update({
  id: '/property-index',
  path: '/property-index',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const WantedRoute = WantedRouteImport.update({
  id: '/wanted',
  path: '/wanted',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenciesIdRoute = AgenciesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AgenciesRoute,
} as any)
const AgentsIdRoute = AgentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AgentsRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const CommunityIdRoute = CommunityIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CommunityRoute,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GuidesRoute,
} as any)
const LocationsCityRoute = LocationsCityRouteImport.update({
  id: '/$city',
  path: '/$city',
  getParentRoute: () => LocationsRoute,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectsRoute,
} as any)
const PropertyIdRoute = PropertyIdRouteImport.update({
  id: '/property/$id',
  path: '/property/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsCityAreaRoute = LocationsCityAreaRouteImport.update({
  id: '/$area',
  path: '/$area',
  getParentRoute: () => LocationsCityRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add': typeof AddRoute
  '/agencies': typeof AgenciesRouteWithChildren
  '/agents': typeof AgentsRouteWithChildren
  '/alerts': typeof AlertsRoute
  '/blog': typeof BlogRouteWithChildren
  '/cities': typeof CitiesRoute
  '/community': typeof CommunityRouteWithChildren
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/guides': typeof GuidesRouteWithChildren
  '/invest': typeof InvestRoute
  '/loans': typeof LoansRoute
  '/locations': typeof LocationsRouteWithChildren
  '/login': typeof LoginRoute
  '/maps': typeof MapsRoute
  '/my-ads': typeof MyAdsRoute
  '/orders': typeof OrdersRoute
  '/pay': typeof PayRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/property-index': typeof PropertyIndexRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRouteWithChildren
  '/tools': typeof ToolsRoute
  '/trends': typeof TrendsRoute
  '/wanted': typeof WantedRoute
  '/agencies/$id': typeof AgenciesIdRoute
  '/agents/$id': typeof AgentsIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/community/$id': typeof CommunityIdRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/locations/$city': typeof LocationsCityRouteWithChildren
  '/projects/$id': typeof ProjectsIdRoute
  '/property/$id': typeof PropertyIdRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/locations/$city/$area': typeof LocationsCityAreaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add': typeof AddRoute
  '/agencies': typeof AgenciesRouteWithChildren
  '/agents': typeof AgentsRouteWithChildren
  '/alerts': typeof AlertsRoute
  '/blog': typeof BlogRouteWithChildren
  '/cities': typeof CitiesRoute
  '/community': typeof CommunityRouteWithChildren
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/guides': typeof GuidesRouteWithChildren
  '/invest': typeof InvestRoute
  '/loans': typeof LoansRoute
  '/locations': typeof LocationsRouteWithChildren
  '/login': typeof LoginRoute
  '/maps': typeof MapsRoute
  '/my-ads': typeof MyAdsRoute
  '/orders': typeof OrdersRoute
  '/pay': typeof PayRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/property-index': typeof PropertyIndexRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRouteWithChildren
  '/tools': typeof ToolsRoute
  '/trends': typeof TrendsRoute
  '/wanted': typeof WantedRoute
  '/agencies/$id': typeof AgenciesIdRoute
  '/agents/$id': typeof AgentsIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/community/$id': typeof CommunityIdRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/locations/$city': typeof LocationsCityRouteWithChildren
  '/projects/$id': typeof ProjectsIdRoute
  '/property/$id': typeof PropertyIdRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/locations/$city/$area': typeof LocationsCityAreaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add': typeof AddRoute
  '/agencies': typeof AgenciesRouteWithChildren
  '/agents': typeof AgentsRouteWithChildren
  '/alerts': typeof AlertsRoute
  '/blog': typeof BlogRouteWithChildren
  '/cities': typeof CitiesRoute
  '/community': typeof CommunityRouteWithChildren
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/guides': typeof GuidesRouteWithChildren
  '/invest': typeof InvestRoute
  '/loans': typeof LoansRoute
  '/locations': typeof LocationsRouteWithChildren
  '/login': typeof LoginRoute
  '/maps': typeof MapsRoute
  '/my-ads': typeof MyAdsRoute
  '/orders': typeof OrdersRoute
  '/pay': typeof PayRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/property-index': typeof PropertyIndexRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRouteWithChildren
  '/tools': typeof ToolsRoute
  '/trends': typeof TrendsRoute
  '/wanted': typeof WantedRoute
  '/agencies/$id': typeof AgenciesIdRoute
  '/agents/$id': typeof AgentsIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/community/$id': typeof CommunityIdRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/locations/$city': typeof LocationsCityRouteWithChildren
  '/projects/$id': typeof ProjectsIdRoute
  '/property/$id': typeof PropertyIdRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/locations/$city/$area': typeof LocationsCityAreaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/add'
    | '/agencies'
    | '/agents'
    | '/alerts'
    | '/blog'
    | '/cities'
    | '/community'
    | '/compare'
    | '/contact'
    | '/guides'
    | '/invest'
    | '/loans'
    | '/locations'
    | '/login'
    | '/maps'
    | '/my-ads'
    | '/orders'
    | '/pay'
    | '/projects'
    | '/property-index'
    | '/saved'
    | '/search'
    | '/services'
    | '/tools'
    | '/trends'
    | '/wanted'
    | '/agencies/$id'
    | '/agents/$id'
    | '/blog/$slug'
    | '/community/$id'
    | '/guides/$slug'
    | '/locations/$city'
    | '/projects/$id'
    | '/property/$id'
    | '/services/$slug'
    | '/api/auth/$'
    | '/locations/$city/$area'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/add'
    | '/agencies'
    | '/agents'
    | '/alerts'
    | '/blog'
    | '/cities'
    | '/community'
    | '/compare'
    | '/contact'
    | '/guides'
    | '/invest'
    | '/loans'
    | '/locations'
    | '/login'
    | '/maps'
    | '/my-ads'
    | '/orders'
    | '/pay'
    | '/projects'
    | '/property-index'
    | '/saved'
    | '/search'
    | '/services'
    | '/tools'
    | '/trends'
    | '/wanted'
    | '/agencies/$id'
    | '/agents/$id'
    | '/blog/$slug'
    | '/community/$id'
    | '/guides/$slug'
    | '/locations/$city'
    | '/projects/$id'
    | '/property/$id'
    | '/services/$slug'
    | '/api/auth/$'
    | '/locations/$city/$area'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/add'
    | '/agencies'
    | '/agents'
    | '/alerts'
    | '/blog'
    | '/cities'
    | '/community'
    | '/compare'
    | '/contact'
    | '/guides'
    | '/invest'
    | '/loans'
    | '/locations'
    | '/login'
    | '/maps'
    | '/my-ads'
    | '/orders'
    | '/pay'
    | '/projects'
    | '/property-index'
    | '/saved'
    | '/search'
    | '/services'
    | '/tools'
    | '/trends'
    | '/wanted'
    | '/agencies/$id'
    | '/agents/$id'
    | '/blog/$slug'
    | '/community/$id'
    | '/guides/$slug'
    | '/locations/$city'
    | '/projects/$id'
    | '/property/$id'
    | '/services/$slug'
    | '/api/auth/$'
    | '/locations/$city/$area'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AddRoute: typeof AddRoute
  AgenciesRoute: typeof AgenciesRouteWithChildren
  AgentsRoute: typeof AgentsRouteWithChildren
  AlertsRoute: typeof AlertsRoute
  BlogRoute: typeof BlogRouteWithChildren
  CitiesRoute: typeof CitiesRoute
  CommunityRoute: typeof CommunityRouteWithChildren
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  GuidesRoute: typeof GuidesRouteWithChildren
  InvestRoute: typeof InvestRoute
  LoansRoute: typeof LoansRoute
  LocationsRoute: typeof LocationsRouteWithChildren
  LoginRoute: typeof LoginRoute
  MapsRoute: typeof MapsRoute
  MyAdsRoute: typeof MyAdsRoute
  OrdersRoute: typeof OrdersRoute
  PayRoute: typeof PayRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  PropertyIndexRoute: typeof PropertyIndexRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  ToolsRoute: typeof ToolsRoute
  TrendsRoute: typeof TrendsRoute
  WantedRoute: typeof WantedRoute
  PropertyIdRoute: typeof PropertyIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agencies': {
      id: '/agencies'
      path: '/agencies'
      fullPath: '/agencies'
      preLoaderRoute: typeof AgenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities': {
      id: '/cities'
      path: '/cities'
      fullPath: '/cities'
      preLoaderRoute: typeof CitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invest': {
      id: '/invest'
      path: '/invest'
      fullPath: '/invest'
      preLoaderRoute: typeof InvestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans': {
      id: '/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof LoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps': {
      id: '/maps'
      path: '/maps'
      fullPath: '/maps'
      preLoaderRoute: typeof MapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-ads': {
      id: '/my-ads'
      path: '/my-ads'
      fullPath: '/my-ads'
      preLoaderRoute: typeof MyAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property-index': {
      id: '/property-index'
      path: '/property-index'
      fullPath: '/property-index'
      preLoaderRoute: typeof PropertyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wanted': {
      id: '/wanted'
      path: '/wanted'
      fullPath: '/wanted'
      preLoaderRoute: typeof WantedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agencies/$id': {
      id: '/agencies/$id'
      path: '/$id'
      fullPath: '/agencies/$id'
      preLoaderRoute: typeof AgenciesIdRouteImport
      parentRoute: typeof AgenciesRoute
    }
    '/agents/$id': {
      id: '/agents/$id'
      path: '/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof AgentsIdRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/community/$id': {
      id: '/community/$id'
      path: '/$id'
      fullPath: '/community/$id'
      preLoaderRoute: typeof CommunityIdRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/locations/$city': {
      id: '/locations/$city'
      path: '/$city'
      fullPath: '/locations/$city'
      preLoaderRoute: typeof LocationsCityRouteImport
      parentRoute: typeof LocationsRoute
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/property/$id': {
      id: '/property/$id'
      path: '/property/$id'
      fullPath: '/property/$id'
      preLoaderRoute: typeof PropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$city/$area': {
      id: '/locations/$city/$area'
      path: '/$area'
      fullPath: '/locations/$city/$area'
      preLoaderRoute: typeof LocationsCityAreaRouteImport
      parentRoute: typeof LocationsCityRoute
    }
  }
}

interface AgenciesRouteChildren {
  AgenciesIdRoute: typeof AgenciesIdRoute
}

const AgenciesRouteChildren: AgenciesRouteChildren = {
  AgenciesIdRoute: AgenciesIdRoute,
}

const AgenciesRouteWithChildren = AgenciesRoute._addFileChildren(
  AgenciesRouteChildren,
)

interface AgentsRouteChildren {
  AgentsIdRoute: typeof AgentsIdRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsIdRoute: AgentsIdRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface CommunityRouteChildren {
  CommunityIdRoute: typeof CommunityIdRoute
}

const CommunityRouteChildren: CommunityRouteChildren = {
  CommunityIdRoute: CommunityIdRoute,
}

const CommunityRouteWithChildren = CommunityRoute._addFileChildren(
  CommunityRouteChildren,
)

interface GuidesRouteChildren {
  GuidesSlugRoute: typeof GuidesSlugRoute
}

const GuidesRouteChildren: GuidesRouteChildren = {
  GuidesSlugRoute: GuidesSlugRoute,
}

const GuidesRouteWithChildren =
  GuidesRoute._addFileChildren(GuidesRouteChildren)

interface LocationsCityRouteChildren {
  LocationsCityAreaRoute: typeof LocationsCityAreaRoute
}

const LocationsCityRouteChildren: LocationsCityRouteChildren = {
  LocationsCityAreaRoute: LocationsCityAreaRoute,
}

const LocationsCityRouteWithChildren = LocationsCityRoute._addFileChildren(
  LocationsCityRouteChildren,
)

interface LocationsRouteChildren {
  LocationsCityRoute: typeof LocationsCityRouteWithChildren
}

const LocationsRouteChildren: LocationsRouteChildren = {
  LocationsCityRoute: LocationsCityRouteWithChildren,
}

const LocationsRouteWithChildren = LocationsRoute._addFileChildren(
  LocationsRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsIdRoute: typeof ProjectsIdRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIdRoute: ProjectsIdRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AddRoute: AddRoute,
  AgenciesRoute: AgenciesRouteWithChildren,
  AgentsRoute: AgentsRouteWithChildren,
  AlertsRoute: AlertsRoute,
  BlogRoute: BlogRouteWithChildren,
  CitiesRoute: CitiesRoute,
  CommunityRoute: CommunityRouteWithChildren,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  GuidesRoute: GuidesRouteWithChildren,
  InvestRoute: InvestRoute,
  LoansRoute: LoansRoute,
  LocationsRoute: LocationsRouteWithChildren,
  LoginRoute: LoginRoute,
  MapsRoute: MapsRoute,
  MyAdsRoute: MyAdsRoute,
  OrdersRoute: OrdersRoute,
  PayRoute: PayRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  PropertyIndexRoute: PropertyIndexRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  ServicesRoute: ServicesRouteWithChildren,
  ToolsRoute: ToolsRoute,
  TrendsRoute: TrendsRoute,
  WantedRoute: WantedRoute,
  PropertyIdRoute: PropertyIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
